### ISSUE TITLE
More documentation on the setup of this?

### ISSUE THREAD

**Issue by tiefpunkt** [Open-Workshop-Network/Theme#1]
Hi!
I'm looking to use this for two projects, http://munichmakes.de and http://www.kreativquartier-muenchen.de/, but I'm struggling to set this up. I got the theme installed on Wordpress, and noted I also need the "Advanced Custom Fields" extension, but is there any additional information on how to configure that extension, as to what fields are needed, or if there are any additional extensions required?
Thanks,
Severin

**Comment by unknowndomain** [comment]
I think this is fixed, try `git pull` or download the Zip file again with the new change.
